const places = [
  {
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima qui harum repudiandae, eligendi labore provident culpa commodi laboriosam deserunt fuga. Aut incidunt laudantium sequi quod minus! Est itaque corporis quisquam.',
    distance: 5,
    id: 1,
    image: 'https://static1.squarespace.com/static/55b7ea68e4b0be339cc75dad/t/55b805a8e4b0a6b779d3af11/1438123434780/Nightclub+Shooting+Lawsuit.jpg?format=1500w',
    lat: 44.8147883,
    long: 20.4492903,
    name: 'Brankow Club',
    popularity: 100,
    street: 'Baba Visnjina 45 / 5',
    type: 'Club',
  },
  {
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima qui harum repudiandae, eligendi labore provident culpa commodi laboriosam deserunt fuga. Aut incidunt laudantium sequi quod minus! Est itaque corporis quisquam.',
    distance: 7.7,
    id: 2,
    image: 'https://www.scandichotels.com/imagevault/publishedmedia/qn6infvg30381stkubky/scandic-sundsvall-city-restaurant-verket-10.jpg',
    lat: 44.8159756,
    long: 20.4447949,
    name: 'Splav TAG',
    popularity: 90,
    street: 'Baba Visnjina 45 / 5',
    type: 'Restaurant',
  },
  {
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima qui harum repudiandae, eligendi labore provident culpa commodi laboriosam deserunt fuga. Aut incidunt laudantium sequi quod minus! Est itaque corporis quisquam.',
    distance: 2.5,
    id: 3,
    image: 'https://static1.squarespace.com/static/55b7ea68e4b0be339cc75dad/t/55b805a8e4b0a6b779d3af11/1438123434780/Nightclub+Shooting+Lawsuit.jpg?format=1500w',
    lat: 44.8159756,
    long: 20.4447949,
    name: 'Hot Mess',
    popularity: 90,
    street: 'Baba Visnjina 45 / 5',
    type: 'Club',
  },
  {
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima qui harum repudiandae, eligendi labore provident culpa commodi laboriosam deserunt fuga. Aut incidunt laudantium sequi quod minus! Est itaque corporis quisquam.',
    distance: 0.5,
    id: 4,
    image: 'https://ats-alltopstartups.netdna-ssl.com//wp-content/uploads/2016/12/How-to-Open-a-Coffee-Shop-.png',
    lat: 44.8200472,
    long: 20.443765,
    name: 'Shake n Shake',
    popularity: 77,
    street: 'Baba Visnjina 45 / 5',
    type: 'Cafe',
  },
  {
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima qui harum repudiandae, eligendi labore provident culpa commodi laboriosam deserunt fuga. Aut incidunt laudantium sequi quod minus! Est itaque corporis quisquam.',
    distance: 20,
    id: 5,
    image: 'https://static1.squarespace.com/static/55b7ea68e4b0be339cc75dad/t/55b805a8e4b0a6b779d3af11/1438123434780/Nightclub+Shooting+Lawsuit.jpg?format=1500w',
    lat: 44.7981075,
    long: 20.4176856,
    name: 'Club Underground',
    popularity: 95,
    street: 'Baba Visnjina 45 / 5',
    type: 'Bar',
  },
  {
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima qui harum repudiandae, eligendi labore provident culpa commodi laboriosam deserunt fuga. Aut incidunt laudantium sequi quod minus! Est itaque corporis quisquam.',
    distance: 20.5,
    id: 6,
    image: 'https://static1.squarespace.com/static/55b7ea68e4b0be339cc75dad/t/55b805a8e4b0a6b779d3af11/1438123434780/Nightclub+Shooting+Lawsuit.jpg?format=1500w',
    lat: 44.8207543,
    long: 20.4478283,
    name: 'Club Gotik',
    popularity: 79,
    street: 'Baba Visnjina 45 / 5',
    type: 'Club',
  },
  {
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima qui harum repudiandae, eligendi labore provident culpa commodi laboriosam deserunt fuga. Aut incidunt laudantium sequi quod minus! Est itaque corporis quisquam.',
    distance: 10.7,
    id: 7,
    image: 'https://static1.squarespace.com/static/55b7ea68e4b0be339cc75dad/t/55b805a8e4b0a6b779d3af11/1438123434780/Nightclub+Shooting+Lawsuit.jpg?format=1500w',
    lat: 44.7981658,
    long: 20.4176856,
    name: 'Mr Stefan Braun',
    popularity: 92,
    street: 'Baba Visnjina 45 / 5',
    type: 'Club',
  },
  {
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima qui harum repudiandae, eligendi labore provident culpa commodi laboriosam deserunt fuga. Aut incidunt laudantium sequi quod minus! Est itaque corporis quisquam.',
    distance: 9.9,
    id: 8,
    image: 'https://static1.squarespace.com/static/55b7ea68e4b0be339cc75dad/t/55b805a8e4b0a6b779d3af11/1438123434780/Nightclub+Shooting+Lawsuit.jpg?format=1500w',
    lat: 44.8181355,
    long: 20.4486223,
    name: 'The Bank',
    popularity: 99,
    street: 'Baba Visnjina 45 / 5',
    type: 'Club',
  },
  {
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima qui harum repudiandae, eligendi labore provident culpa commodi laboriosam deserunt fuga. Aut incidunt laudantium sequi quod minus! Est itaque corporis quisquam.',
    distance: 3.7,
    id: 9,
    image: 'https://static1.squarespace.com/static/55b7ea68e4b0be339cc75dad/t/55b805a8e4b0a6b779d3af11/1438123434780/Nightclub+Shooting+Lawsuit.jpg?format=1500w',
    lat: 44.7982822,
    long: 20.4176856,
    name: 'Klub Knjizevnika',
    popularity: 65,
    street: 'Baba Visnjina 45 / 5',
    type: 'Restaurant',
  },
  {
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima qui harum repudiandae, eligendi labore provident culpa commodi laboriosam deserunt fuga. Aut incidunt laudantium sequi quod minus! Est itaque corporis quisquam.',
    distance: 7.7,
    id: 10,
    image: 'https://nyc-wpengine.netdna-ssl.com/wp-content/uploads/2017/01/20140423_Es_bar-9571_ENF.tif.jpg',
    lat: 44.8137126,
    long: 20.4498084,
    name: 'Tranzit Bar',
    popularity: 95,
    street: 'Baba Visnjina 45 / 5',
    type: 'Bar',
  },
  {
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima qui harum repudiandae, eligendi labore provident culpa commodi laboriosam deserunt fuga. Aut incidunt laudantium sequi quod minus! Est itaque corporis quisquam.',
    distance: 5.9,
    id: 11,
    image: 'http://www.rakiabar.com/upload/images/gallery/Rb_Toronto_Annex/pic1.JPG',
    lat: 44.817451,
    long: 20.4657835,
    name: 'Zaokret',
    popularity: 98,
    street: 'Baba Visnjina 45 / 5',
    type: 'Bar',
  },
  {
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima qui harum repudiandae, eligendi labore provident culpa commodi laboriosam deserunt fuga. Aut incidunt laudantium sequi quod minus! Est itaque corporis quisquam.',
    distance: 10.7,
    id: 12,
    image: 'https://static1.squarespace.com/static/55b7ea68e4b0be339cc75dad/t/55b805a8e4b0a6b779d3af11/1438123434780/Nightclub+Shooting+Lawsuit.jpg?format=1500w',
    lat: 44.798047,
    long: 20.435324,
    name: 'Splav Lasta',
    popularity: 94,
    street: 'Baba Visnjina 45 / 5',
    type: 'Club',
  },
];

const initialState = {
  places,
  sorting: '',
  showing: 'all',
  filters: [
    { id: 'club', inuse: false },
    { id: 'restaurant', inuse: false },
    { id: 'cafe', inuse: false },
    { id: 'bar', inuse: false },
  ],
};

export default function (state = initialState, action) {
  switch (action.type) {
    case 'SET_SHOWING':
      return {
        ...state,
        showing: action.payload,
      };
    case 'SET_SORTING':
      return {
        ...state,
        sorting: action.payload,
      };
    default:
      return state;
  }
}
